from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import account_payment
from . import stock_warehouse
from . import sale_order
from . import fleet_sales_visit_customer_stock_line
from . import fleet_sales_visit
from . import fleet_sales_visit_report_wizard
