-- Fast Financial Reports - optional recommended indexes
-- =======================================================
--
-- IMPORTANT: this script is NOT executed automatically by the module, on
-- install, upgrade, or ever. It is a documented, reviewed, manually-applied
-- artifact for a DBA/administrator to run during a maintenance window on a
-- specific production database, after validating the "before" evidence in
-- README.md ("SQL architecture and index analysis") against that database's
-- own EXPLAIN ANALYZE output - not blindly.
--
-- Both indexes below use CREATE INDEX CONCURRENTLY, which builds the index
-- without taking a table-level lock that would block reads/writes on
-- account_move_line (the trade-off is a slower build and a small chance of
-- needing to retry if it's ever interrupted - see PostgreSQL docs on
-- CREATE INDEX CONCURRENTLY for the "invalid index" cleanup procedure).
--
-- Do not run CREATE INDEX CONCURRENTLY inside a transaction block / BEGIN.

-- ---------------------------------------------------------------------
-- 1. (company_id, date) WHERE parent_state = 'posted'
-- ---------------------------------------------------------------------
-- Considered for: Trial Balance / General Ledger summary queries filtered
-- to a NARROW date range within a LARGE company (see
-- wizard/trial_balance.py and wizard/general_ledger.py _ffr_where()).
--
-- Evidence, gathered in TWO rounds at two different table sizes (see
-- README.md and docs/benchmarks/ for the full EXPLAIN ANALYZE output; each
-- figure is the average of 3 runs after ANALYZE, warm cache):
--
--   Round 1, ~5,100,000 rows in the table: ~251ms -> ~230ms (~8% FASTER).
--   The plan switched from a Bitmap Heap Scan on the existing
--   account_move_line_date_name_id_idx to a plain Index Scan on this new
--   index - a small win.
--
--   Round 2, ~10,000,000 rows in the table, SAME query: ~452ms -> ~602ms
--   (~30% SLOWER). At this larger size and result-set cardinality (~117,000
--   matching rows), a plain Index Scan on the new (company_id, date) index
--   visits heap pages in index order - a scattered/random access pattern;
--   the existing plan (Bitmap Heap Scan on
--   account_move_line_date_name_id_idx) collects matching row locations
--   first and then visits heap pages in physical order, which is more
--   I/O-efficient once the result set is large enough. Adding the new
--   index tempted PostgreSQL's planner into the WORSE plan for this exact
--   query shape at this scale. Confirmed reproducible: dropping the index
--   again restored the faster Bitmap Heap Scan plan (459ms).
--
-- This is a genuine, measured example of exactly why "do not add indexes
-- blindly" matters: the SAME index, on the SAME query shape, went from a
-- modest win to a real regression purely because the table grew and the
-- matching row count crossed the threshold where PostgreSQL's own
-- Bitmap-Heap-Scan-vs-Index-Scan tradeoff flips. A conclusion drawn from
-- one data size does not necessarily hold at another.
--
-- For a SMALL company sharing a database with many other companies (the
-- realistic multi-company case this table is usually in), the existing
-- single-column account_move_line__company_id_index (already shipped by
-- Odoo's account module) was already sufficient in both rounds - this
-- composite index gave no further improvement there either.
--
-- Recommendation: NOT RECOMMENDED (revised after round 2). The round-1
-- finding (a modest win at 5.1M rows) does not hold at 10M rows, where the
-- same index measurably hurts the same query. Given the module's own
-- target scale is ~75M rows - well past where this reversal already
-- appeared at 10M - applying this index without re-validating against the
-- actual production data size and distribution first would be exactly the
-- "blind index" this policy exists to prevent. Left here, disabled
-- (commented out below), for the record.
--
-- Write/storage overhead (if you still choose to test this on a staging
-- copy of production, despite the recommendation above): adds one index
-- entry per posted account_move_line row. At 75,000,000 lines, expect
-- roughly 1.5-2.5 GB of additional index size (rule of thumb only -
-- verify with pg_relation_size() after a CONCURRENT build on staging).

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS account_move_line_ffr_company_date_idx
--     ON account_move_line (company_id, date)
--     WHERE parent_state = 'posted';

-- To remove it again, if you applied it anyway (safe, reversible, does
-- not lock the table):
-- DROP INDEX CONCURRENTLY IF EXISTS account_move_line_ffr_company_date_idx;


-- ---------------------------------------------------------------------
-- 2. (company_id, partner_id, date) WHERE parent_state = 'posted' AND
--    partner_id IS NOT NULL
-- ---------------------------------------------------------------------
-- Considered for: Partner Ledger summary queries (wizard/partner_ledger.py).
--
-- Evidence: EXPLAIN ANALYZE at 5,100,000 rows shows PostgreSQL's planner
-- continuing to prefer the existing account_move_line_account_id_date_idx
-- combined with account_move_line_partner_id_ref_idx (a BitmapAnd of the
-- two) over this new index, with no statistically significant wall-clock
-- improvement (430ms vs 375ms, within run-to-run noise on this hardware).
-- Re-tested at 10,000,000 rows (round 2 of QA): same result - the planner
-- still does not use this index at all (confirmed by reading the actual
-- EXPLAIN plan, not just timing: it still shows a BitmapAnd of the two
-- existing indexes), and wall-clock time is unchanged within noise
-- (~822-960ms before, ~845-934ms after). Unlike candidate #1 above, this
-- conclusion is STABLE across both tested scales.
--
-- Recommendation: NOT RECOMMENDED based on the evidence gathered for this
-- module, at both tested scales. The existing indexes already cover this
-- access pattern reasonably well. Left here, disabled, for the record - do
-- not apply this one without first re-running EXPLAIN ANALYZE on your own
-- production data and query shapes, since a genuinely different partner
-- cardinality or account distribution could still change this conclusion.
--
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS account_move_line_ffr_company_partner_date_idx
--     ON account_move_line (company_id, partner_id, date)
--     WHERE parent_state = 'posted' AND partner_id IS NOT NULL;
